constraintsPath: "./.yarn/constraints.pro"

packageExtensions:
  pino@*:
    dependencies:
      pino-pretty: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
