constraintsPath: "./.yarn/constraints.pro"

packageExtensions:
  pino@*:
    dependencies:
      pino-pretty: "^4.0.3"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "^0.3.6"
  "@protobufjs/inquire@*":
     dependencies:
       long: "^5.2.0"
  ts-node@*:
    dependencies:
      typescript: "^3.9.5"
  karma-mocha@*:
    dependencies:
      mocha: "^9.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
