name: Package Tests

on:
  release:
    types:
      - published
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev

jobs:
  test:
    name: Test Dash Platform component
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3
          install: true
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Enable NPM cache
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Enable buildkit cache
        uses: actions/cache@v2
        with:
          path: /tmp/buildkit-cache/buildkit-state.tar
          key: ${{ runner.os }}-buildkit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-

      - name: Load buildkit state from cache
        uses: dashevo/gh-action-cache-buildkit-state@v1
        with:
          builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
          cache-path: /tmp/buildkit-cache
          cache-max-size: 3g

      - name: Setup repo and local network
        run: npm run setup

      - name: Run Packster
        run: node_modules/.bin/packster check --all --error

      - name: Run ESLinter
        run: npm run lint

      - name: Get list of packages to test
        id: packster
        run: echo "::set-output name=dependants::$(packster list ${{ inputs.package }} --json)"

      - name: Start local network
        run: npm run start

      - name: Run tests on packages
        run: npm run test

